version: "3"

services:
  wordpress:
    volumes:
      - "./src/vip-go-mu-plugins/drop-ins/object-cache/object-cache.php:/var/www/html/wp-content/object-cache.php:ro"
  memcached:
    image: "memcached:1.5"
    networks:
      - "back"
